config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions" }

  root 'restaurants#index'

  get 'restaurants/:id', to: 'restaurants#show', as: :restaurant

  get 'articles/:id' => 'articles#show', as: :article

  post 'favorites' => 'favorites#create'

  post 'comments' => 'comments#create'

  namespace :admin do
    resources :articles
    resources :banners
    resources :categories
    resources :restaurants
  end

  scope :admin do
    root 'admin#dashboard', as: :admin_root
  end
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Article < ActiveRecord::Base
  has_one :banner

  attr_accessor :banner_id

  before_save :set_banner

  validates :title, presence: true, uniqueness: true
  validates :content, presence: true

  private

  def set_banner
    if banner_id
      Banner.where(article_id: self.id).update_all({article_id: nil})

      banner = Banner.where(id: banner_id).first
      banner.update(article_id: self.id) if banner
    end
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(articles_params)
    if @article.save
      redirect_to admin_articles_path
    else
      render :new
    end
  end

  def show
  end


  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(articles_params)
      redirect_to admin_articles_path
    else
      render :edit
    end
  end

  private

  def articles_params
    params.require(:article).permit(:title, :content, :banner_id)
  end
end

app/controllers/articles_controller.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ArticlesController < ApplicationController
  def show
    @article = Article.find(params[:id])
  end
end

app/views/admin/articles/_form.html.erb
<script src="//cdn.ckeditor.com/4.5.9/full/ckeditor.js"></script>

<%= form_for [:admin, @article] do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :content, :class => 'control-label' %>
      <%= f.text_area :content, :class => 'form-control ckeditor' %>
    </div>

    <div class="form-group">
      <%= f.label :banner %>
      <%= f.collection_select(:banner_id, Banner.all, :id, :name, {:selected => @article.banner.id}) %>
    </div>

    <%= f.submit nil, class: 'btn btn-success' %>
    <%=  link_to 'Cancel', admin_articles_path, class: 'btn btn-default', style: 'margin-left: 15px;' %>
<% end %>

app/views/admin/articles/edit.html.erb
<div class="col-md-10 col-md-offset-1 new-form">
  <h2>
    Edit Article
  </h2>

  <hr>

  <%= render 'form' %>
</div>

app/views/admin/articles/index.html.erb
<div class="col-md-12">
  <div class="pull-left"><h2> List Articles </h2></div>
  <div class="pull-right admin-new-btn">
    <%= link_to 'New Article', new_admin_article_path, class: 'btn btn-primary' %>
  </div>
</div>

<div class="col-md-12">
  <hr>
</div>


<div class="col-md-12">
  <table class="table table-hover">
    <thead>
      <th>Id</th>
      <th>Title</th>
      <th>Content</th>
      <th>Banner</th>
      <th>Actions</th>
    </thead>

    <tbody>
      <% @articles.each do |article| %>
          <tr>
            <td>
              <%= article.id %>
            </td>

            <td>
              <%= article.title%>
            </td>

            <td>
              <%= article.content.truncate(100, omission: '...') %>
            </td>
            <td></td>

            <td>
              <%= link_to 'View', admin_article_path(article), class: "btn btn-default", data: { no_turbolink: true } %>
              <%= link_to 'Edit', edit_admin_article_path(article), class: "btn btn-default", data: { no_turbolink: true } %>
              <%= link_to 'Destroy', admin_article_path(article), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
            </td>
          </tr>
      <% end %>
      </tbody>
  </table>
</div>

app/views/admin/articles/new.html.erb
<div class="col-md-10 col-md-offset-1 new-form">
  <h2>
    New Article
  </h2>

  <hr>

  <%= render 'form' %>
</div>