config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions" }

  root 'restaurants#index'

  get 'restaurants/:id', to: 'restaurants#show', as: :restaurant

  get 'articles/:id' => 'articles#show', as: :article

  post 'favorites' => 'favorites#create'

  post 'comments' => 'comments#create'

  namespace :admin do
    resources :articles
    resources :banners
    resources :categories
    resources :restaurants
  end

  scope :admin do
    root 'admin#dashboard', as: :admin_root
  end
end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id          :integer          not null, primary key
#  name        :string
#  about       :text
#  image       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  location_id :integer
#
# Indexes
#
#  index_restaurants_on_location_id  (location_id)
#

class Restaurant < ActiveRecord::Base
  has_many :cat_res
  has_many :categories, through: :cat_res

  has_many :favorites
  has_many :comments

  belongs_to :location

  validates :name, uniqueness: { scope: :location_id,
                                 message: "A location should not have two duplicated restaurants" }
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < AdminController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to admin_restaurants_path
    else
      render :new
    end
  end
  #
  # def show
  # end
  #
  #
  def edit
    @restaurant = Restaurant.find(params[:id])
  end
  #
  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to admin_restaurants_path
    else
      render :edit
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :about, :image, category_ids: [])
  end
end

app/controllers/restaurants_controller.rb
# == Schema Information
#
# Table name: restaurants
#
#  id          :integer          not null, primary key
#  name        :string
#  about       :text
#  image       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  location_id :integer
#
# Indexes
#
#  index_restaurants_on_location_id  (location_id)
#

class RestaurantsController < ApplicationController
  def index
    @banners = Banner.all.to_a.transform(3)
    @categories = Category.all
  end


  def show
    @restaurant = Restaurant.where(id: params[:id]).first
    @comments = @restaurant.comments
    @new_comment = Comment.new
    if current_user
      @is_liked = Favorite.where(
          user_id: current_user.id, restaurant_id: @restaurant.id
      ).exists?
    end



  end
end

app/views/admin/restaurants/_form.html.erb
<script src="//cdn.ckeditor.com/4.5.9/full/ckeditor.js"></script>

<%= form_for [:admin, @restaurant] do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :about, :class => 'control-label' %>
      <%= f.text_area :about, :class => 'form-control ckeditor' %>
    </div>

    <div class="form-group">
      <%= f.label :image %>
      <%= f.text_field :image,  :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :categories, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |c| %>
            <%= c.label %>
            <span style="margin-left: 5px; position:relative;"> <%= c.check_box %> </span>
            <br>
        <% end %>
      </div>
    </div>

    <%= f.submit nil, class: 'btn btn-success' %>
    <%=  link_to 'About', admin_restaurants_path, class: 'btn btn-default', style: 'margin-left: 15px;' %>
<% end %>

app/views/admin/restaurants/edit.html.erb
<%= render 'form' %>

app/views/admin/restaurants/index.html.erb
<div class="col-md-12">
  <div class="pull-left"><h2> List Restaurant </h2></div>
  <div class="pull-right admin-new-btn">
    <%= link_to 'New Restaurant', new_admin_restaurant_path, class: 'btn btn-primary' %>
  </div>
</div>

<div class="col-md-12">
  <hr>
</div>


<div class="col-md-12">
  <table class="table table-hover">
    <thead>

    <th>Id</th>
    <th>Name</th>
    <th>About</th>
    <th>Image</th>
    <th>Categories</th>
    <th>Actions</th>

    </thead>

    <tbody>
    <% @restaurants.each do |res| %>
        <tr>
          <td>
            <%= res.id %>
          </td>

          <td>
            <%= res.name %>
          </td>

          <td>
            <%= res.about ? res.about.truncate(100, omission: '...') : 'No About description' %>
          </td>
          <td>
            <%= res.image ? image_tag(res.image, width: '150px', height: '150px') : '' %>
          </td>
          <td><%= (res.categories.all.map {|t| t.name}).join(', ') %></td>

          <td>
            <%= link_to 'Edit', edit_admin_restaurant_path(res), class: "btn btn-default", data: { no_turbolink: true } %>
            <%= link_to 'Destroy', admin_restaurant_path(res), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/restaurants/new.html.erb
<%= render 'form' %>