config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions" }

  root 'restaurants#index'

  get 'restaurants/:id', to: 'restaurants#show', as: :restaurant

  get 'articles/:id' => 'articles#show', as: :article

  post 'favorites' => 'favorites#create'

  post 'comments' => 'comments#create'

  namespace :admin do
    resources :articles
    resources :banners
    resources :categories
    resources :restaurants
  end

  scope :admin do
    root 'admin#dashboard', as: :admin_root
  end
end

app/views/admin/shared/_header.html.erb
<nav class="navbar navbar-default" id="admin-navbar">

  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-2" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-2">
    <ul class="nav navbar-nav nav-menu">
      <li>
        <a href="#menu-toggle" id="menu-toggle">
          <i class="fa fa-bars"></i>
        </a>
      </li>
    </ul>

      <ul class="nav navbar-nav nav-menu navbar-right">
        <li><a href="#">Restaurants</a> </li>
        <!--<li><a href="#">Location</a> </li>-->
        <!--<li><a href="#">Category</a> </li>-->
      </ul>
  </div><!-- /.container-fluid -->
</nav>

app/views/admin/shared/_sidebar.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <div class="pull-left">
        <a href="#">
          Admin
        </a>
      </div>

    </li>
    <li>
      <%= link_to 'Banner', admin_banners_path %>
    </li>
    <li>
      <%= link_to 'Article', admin_articles_path %>
    </li>
    <li>
      <%= link_to 'Category', admin_categories_path %>
    </li>
    <li>
      <%= link_to 'Restaurant', admin_restaurants_path %>
    </li>
    <li>
      <a href="#">Location</a>
    </li>

    <li>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
    </li>

  </ul>
</div>
<!-- /#sidebar-wrapper -->